# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := gtk
### Rules for final target.
$(obj).target/gtk.stamp: TOOLSET := $(TOOLSET)
$(obj).target/gtk.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/gtk.stamp
# Add target alias
.PHONY: gtk
gtk: $(obj).target/gtk.stamp

# Add target alias to "all" target.
.PHONY: all
all: gtk

